# scripts/clean_old_plots.py
"""Removes plot files that were generated by older versions of the analysis
scripts and are now superseded by shorter-named equivalents.

Safe to run multiple times — only files matching the known old patterns are
deleted; current output files are left untouched.

Usage::

    python scripts/clean_old_plots.py          # dry run (shows what would go)
    python scripts/clean_old_plots.py --delete  # actually delete
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import glob
import argparse

import config

# ---------------------------------------------------------------------------
# Glob patterns for stale files (relative to the plots root)
# ---------------------------------------------------------------------------
# Each entry is a glob pattern; ** requires recursive=True.

STALE_PATTERNS = [
    # Old LS amplitude:  *_Wave_N_LS_Amplitude.png
    "**/*_Wave_[125]_LS_Amplitude.png",

    # Old LS and NN I/F fit / reconstruction files.
    # New name is *_IF_fit.png; any file with "Reconstruction" in the name is stale.
    # Using a broad substring match avoids unicode issues with · and – in old names.
    "**/*Reconstruction*.png",

    # Old NN amplitude:  *_Wave_N_NN_Amplitude.png
    "**/*_Wave_[125]_NN_Amplitude.png",

    # Old NN component files
    "**/*_Wave_[125]_NN_Cosine_Amplitude.png",
    "**/*_Wave_[125]_NN_Sine_Amplitude.png",
    "**/*_Wave_[125]_NN_psi.png",
    "**/*_Wave_[125]_NN_k.png",

    # Old summary (Wave_N_summary vs current w1_summary)
    "**/*_Wave_[125]_summary.png",

    # Bending-wave tri-stack plots (removed feature)
    "**/*_bending_wave_*.png",
]


def collect_stale(plots_root):
    """Returns a sorted list of stale file paths found under *plots_root*."""
    found = []
    for pattern in STALE_PATTERNS:
        matches = glob.glob(os.path.join(plots_root, pattern), recursive=True)
        found.extend(matches)
    return sorted(set(found))


def main():
    parser = argparse.ArgumentParser(description="Remove stale plot files.")
    parser.add_argument(
        "--delete",
        action="store_true",
        help="Actually delete the files (default is dry-run).",
    )
    args = parser.parse_args()

    plots_root = config._p("plots")
    stale = collect_stale(plots_root)

    if not stale:
        print("No stale files found.")
        return

    mode = "DELETING" if args.delete else "DRY RUN — would delete"
    print(f"{mode} {len(stale)} file(s):\n")

    for path in stale:
        rel = os.path.relpath(path, plots_root)
        print(f"  {rel}")
        if args.delete:
            os.remove(path)

    if not args.delete:
        print(
            f"\nRun with --delete to actually remove these {len(stale)} file(s)."
        )
    else:
        print(f"\nDone. {len(stale)} file(s) removed.")


if __name__ == "__main__":
    main()
